#!/bin/bash

echo ""

g++ -o test main.cpp ./src/InputParameters.cpp ./src/PointCloud.cpp ./src/Distribution.cpp ./src/VDistribution.cpp -I./include -lgsl -lgslcblas -lm -I/usr/local/include/Eigen/src/misc/
./test
# /usr/bin/time -v ./run
rm test

echo ""