#!/bin/bash

echo ""

rm *.log 2>/dev/null
g++ -o test main.cpp ./src/InputParameters.cpp ./src/PointCloud.cpp ./src/Distribution.cpp ./src/VDistribution.cpp -I./include -lgsl -lgslcblas -lm -I${BLAS_INC} -L${BLAS_LIB} -lopenblas
# ./test
/usr/bin/time -v ./test
rm test 2>/dev/null

echo ""